"use client"

import { Sparkles, CheckCircle2, MessageCircle, Zap, Tag, FileText } from "lucide-react"

export function AiConversationInsightsSection() {
  const highlights = [
    {
      icon: CheckCircle2,
      title: "Action Items Generated by AI",
      description: "Automatically track key follow-ups from every conversation.",
    },
    {
      icon: MessageCircle,
      title: "Smart Question Detection",
      description: "Identify important questions raised during meetings.",
    },
    {
      icon: Zap,
      title: "Sentiment Analysis",
      description: "Understand tone and engagement levels.",
    },
    {
      icon: Tag,
      title: "Keyword Extraction",
      description: "Get quick insight into discussion topics.",
    },
    {
      icon: FileText,
      title: "AI Summary",
      description: "Get a concise overview of your meeting.",
    },
  ]

  return (
    <section className="py-12 sm:py-16 md:py-20 lg:py-24 bg-card/30 overflow-hidden">
      <div className="container mx-auto px-4 md:px-6 lg:px-12 xl:px-16">
        {/* Header */}
        <div className="text-center mb-12 md:mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#fac547]/10 border border-[#fac547]/20 backdrop-blur-sm mb-5">
            <Sparkles className="w-3.5 h-3.5 text-[#fac547]" />
            <span className="text-[#fac547] text-xs font-semibold tracking-wide uppercase">Powered by AI</span>
          </div>

          <h2 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold mb-4 text-balance">
            <span className="text-foreground">AI Conversation </span>
            <span className="gradient-text">Insights</span>
          </h2>
          <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto">
            Automatically analyze your meetings with actionable AI insights.
          </p>
        </div>

        {/* Main Content */}
        <div className="max-w-6xl mx-auto">
          {/* Features Grid - Fixed Card Height */}
          <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 md:gap-5 mb-10 md:mb-12">
            {highlights.map((highlight, idx) => {
              const Icon = highlight.icon
              return (
                <div
                  key={idx}
                  className="group relative rounded-2xl overflow-hidden transition-all duration-300 hover:-translate-y-1 h-full"
                >
                  <div className="relative h-full flex flex-col justify-between bg-gradient-to-br from-[#fac547]/10 via-card/60 to-[#fac547]/5 backdrop-blur-xl border border-[#fac547]/20 hover:border-[#fac547]/40 rounded-2xl p-5 md:p-6 transition-all duration-300 shadow-lg shadow-black/20 hover:shadow-[#fac547]/10">
                    {/* Glass shine effect */}
                    <div className="absolute inset-0 bg-gradient-to-br from-white/10 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-2xl pointer-events-none"></div>

                    <div className="relative z-10 flex flex-col items-center text-center flex-grow">
                      <div className="mb-4 flex justify-center">
                        <div className="w-12 h-12 md:w-14 md:h-14 rounded-xl bg-gradient-to-br from-[#fac547]/30 to-[#fac547]/20 backdrop-blur-md border border-[#fac547]/30 flex items-center justify-center group-hover:scale-110 transition-transform duration-300 shadow-lg shadow-[#fac547]/20">
                          <Icon className="w-6 h-6 md:w-7 md:h-7 text-[#fac547]" strokeWidth={2} />
                        </div>
                      </div>

                      <h3 className="text-sm md:text-base font-bold text-foreground mb-2 group-hover:text-[#fac547] transition-colors">
                        {highlight.title}
                      </h3>
                      <p className="text-xs md:text-sm text-muted-foreground leading-relaxed group-hover:text-foreground/80 transition-colors">
                        {highlight.description}
                      </p>
                    </div>

                    {/* Decorative corner accent */}
                    <div className="absolute top-0 right-0 w-16 h-16 bg-gradient-to-bl from-[#fac547]/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-bl-full"></div>
                  </div>
                </div>
              )
            })}
          </div>

          {/* Dashboard Preview */}
          <div className="max-w-3xl mx-auto">
            <div className="relative bg-gradient-to-br from-[#fac547]/10 via-card/60 to-[#fac547]/5 backdrop-blur-xl rounded-2xl border border-[#fac547]/20 overflow-hidden shadow-2xl shadow-black/30">
              <div className="absolute inset-0 bg-gradient-to-br from-white/5 via-transparent to-transparent opacity-50 rounded-2xl pointer-events-none"></div>

              {/* Browser Header */}
              <div className="relative bg-black/40 backdrop-blur-md border-b border-[#fac547]/20 px-4 md:px-6 py-3 flex items-center gap-3">
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80 shadow-sm"></div>
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80 shadow-sm"></div>
                  <div className="w-3 h-3 rounded-full bg-green-500/80 shadow-sm"></div>
                </div>
                <div className="flex-1 text-center">
                  <p className="text-xs text-muted-foreground font-medium">AI Analysis Dashboard</p>
                </div>
                <div className="flex items-center gap-2 bg-[#fac547]/20 backdrop-blur-md px-3 py-1 rounded-full border border-[#fac547]/30 shadow-lg shadow-[#fac547]/10">
                  <Sparkles className="w-3 h-3 text-[#fac547]" />
                  <span className="text-xs font-semibold text-[#fac547]">AI Generated</span>
                </div>
              </div>

              {/* Image */}
              <div className="relative bg-gradient-to-br from-background/80 to-background/60 backdrop-blur-sm p-4 md:p-6">
                <img
                  src="https://client-static.saleassist.ai/9eb1c850-96f3-480a-9fa5-392733431de6/AIanalysis"
                  alt="AI-generated conversation analysis dashboard"
                  className="w-full h-auto rounded-lg shadow-2xl border border-[#fac547]/10"
                />
              </div>
            </div>
          </div>

          {/* Bottom Text */}
          <div className="text-center mt-10 md:mt-12">
            <p className="text-base md:text-lg text-muted-foreground max-w-2xl mx-auto">
              See how AIVA transforms your conversations into actionable insights in real-time.
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}
